SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/Score_Submission__c.object-meta.xml
<CustomObject>
    <label>Score Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Score Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Athlete_Name__c.field-meta.xml
<CustomField>
    <fullName>Athlete_Name__c</fullName>
    <inlineHelpText>Select the Athlete&apos;s Name</inlineHelpText>
    <label>Athlete&apos;s Name</label>
    <referenceTo>Athlete__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Score_1st__c.field-meta.xml
<CustomField>
    <fullName>Score_1st__c</fullName>
    <inlineHelpText>1st Value (Mins or Rounds)</inlineHelpText>
    <label>Score (1st)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Vault_Workout__c.field-meta.xml
<CustomField>
    <fullName>Vault_Workout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the Vault Workout</inlineHelpText>
    <label>Vault Workout</label>
    <referenceTo>Vault_Workout__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/Vault_Workout__c.object-meta.xml
<CustomObject>
    <label>Vault Workout</label>
    <nameField>
        <label>Vault Workouts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vault Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/classes/workoutDisplayObject.cls
public without sharing class workoutDisplayObject {
    public Id Id;
    public String Name;
    public String AccordionTitle;
    public String PlainDescription;
    public String Description;
    public String FirstLabel;
    public String SecondLabel;
    public Decimal Order;
    public String Goal;
    public String ImageFile;
    public Decimal RXWeightMale;
    public String URL;
    public Date WorkoutDate;
    public String topScoreString;

    public List<Score_Submission__c> Top3Scores;

    
}

/*
workoutDisplayObject top3 = new workoutDisplayObject();
top3.Name = 'Workout 1';
top3.Order = 1;
top3.Goal = 'Goal 1';
List<Score_Submission__c> top = new List<Score_Submission__c>();
for (Integer i = 0; i < 3; i++) {
    Score_Submission__c ss = new Score_Submission__c(
        Athlete_Name__c = 'a005e000003p5GTAAY',
        Vault_Workout__c = 'a025e0000036fsMAAQ',
        Score_1st__c = 120 + i
    );
    top.add(ss);
}
top3.Top3Scores = top;
System.debug(top3);
*/