SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/Score_Submission__c.object-meta.xml
<CustomObject>
    <label>Score Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Score Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Athlete_Name__c.field-meta.xml
<CustomField>
    <fullName>Athlete_Name__c</fullName>
    <inlineHelpText>Select the Athlete&apos;s Name</inlineHelpText>
    <label>Athlete&apos;s Name</label>
    <referenceTo>Athlete__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Is_Score_Between_Goal__c.field-meta.xml
<CustomField>
    <fullName>Is_Score_Between_Goal__c</fullName>
    <formula>IF(Vault_Workout__r.Is_Goal_Time__c, 
  IF(Weight_Used__c &gt;= Vault_Workout__r.RX_Weight_Male__c, IF(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, 100, 0), IF(AND(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c), 100, 0)
  ), 

  IF(Weight_Used__c &gt;= Vault_Workout__r.RX_Weight_Male__c, IF(Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c, 100, 0), IF(AND(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c), 100, 0)
  )

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Score Between Goal?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Points_Based_on_Rank__c.field-meta.xml
<CustomField>
    <fullName>Points_Based_on_Rank__c</fullName>
    <label>Points Based on Rank</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Score_1st__c.field-meta.xml
<CustomField>
    <fullName>Score_1st__c</fullName>
    <inlineHelpText>1st Value (Mins or Rounds)</inlineHelpText>
    <label>Score (1st)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Score_2nd__c.field-meta.xml
<CustomField>
    <fullName>Score_2nd__c</fullName>
    <inlineHelpText>2nd Value (Secs or Reps)</inlineHelpText>
    <label>Score (2nd)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Total_Workout_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Workout_Points__c</fullName>
    <inlineHelpText>Goal based points + Points based on Rank</inlineHelpText>
    <label>Total Workout Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Vault_Workout__c.field-meta.xml
<CustomField>
    <fullName>Vault_Workout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the Vault Workout</inlineHelpText>
    <label>Vault Workout</label>
    <referenceTo>Vault_Workout__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Weight_Used__c.field-meta.xml
<CustomField>
    <fullName>Weight_Used__c</fullName>
    <inlineHelpText>Weight Used in Workout</inlineHelpText>
    <label>Weight Used</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/Vault_Workout__c.object-meta.xml
<CustomObject>
    <label>Vault Workout</label>
    <nameField>
        <label>Vault Workouts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vault Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/classes/createScoreSubmission.cls
public without sharing class createScoreSubmission {
    @AuraEnabled
    public static Score_Submission__c createScore(Score_Submission__c score) {
        Score_Submission__c[] allScoreSubs = [
            SELECT Id, Name, Athlete_Name__c, Vault_Workout__c, Notes__c, Score_1st__c, Score_2nd__c, Weight_Used__c
            FROM Score_Submission__c
            WHERE Athlete_Name__c = :score.Athlete_Name__c 
            AND Vault_Workout__c = :score.Vault_Workout__c
            // LIMIT 1
        ];
        System.debug('score: ' + score);
        if (allScoreSubs.size() > 0) {
            allScoreSubs[0].Score_1st__c = score.Score_1st__c;
            allScoreSubs[0].Score_2nd__c = score.Score_2nd__c;
            allScoreSubs[0].Weight_Used__c = score.Weight_Used__c;
            System.debug('allScoreSubs(updated): ' + allScoreSubs);
            update allScoreSubs;
        } else {
            System.debug('allScoreSubs: ' + allScoreSubs);
            insert score;
        }
        return score;
    }

    @AuraEnabled
    public static Score_Submission__c getSubmittedScore(Score_Submission__c score) {
        System.debug('getSubmittedScore: ' + score);
        return [
            SELECT Id, Name, Athlete_Name__c, Vault_Workout__c, Notes__c, Score_1st__c, Score_2nd__c, Weight_Used__c, CreatedBy.Name, Is_Score_Between_Goal__c, Total_Workout_Points__c, Points_Based_on_Rank__c 
            FROM Score_Submission__c 
            WHERE Athlete_Name__c = :score.Athlete_Name__c AND Vault_Workout__c = :score.Vault_Workout__c
            LIMIT 1];
    }
}