SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/Score_Submission__c.object-meta.xml
<CustomObject>
    <label>Score Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Score Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Calculated_Ranking_Points__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Ranking_Points__c</fullName>
    <formula>IF( 
Vault_Workout__r.Is_Dumbbell__c , 
Calculated_Points__c + Calculated_Points__c * (0.01 * Weight_Used__c + 0.6), 
Calculated_Points__c + Calculated_Points__c * (0.005 * Weight_Used__c + 0.525)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Ranking Points</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Is_Goal_Time__c.field-meta.xml
<CustomField>
    <fullName>Is_Goal_Time__c</fullName>
    <formula>Vault_Workout__r.Is_Goal_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Goal Time?</label>
    <type>Checkbox</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Is_Score_Between_Goal__c.field-meta.xml
<CustomField>
    <fullName>Is_Score_Between_Goal__c</fullName>
    <formula>IF(Vault_Workout__r.Is_Goal_Time__c, 
  IF(Weight_Used__c &gt;= Vault_Workout__r.RX_Weight_Male__c, IF(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, 100, 0), IF(AND(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c), 100, 0)
  ), 

  IF(Weight_Used__c &gt;= Vault_Workout__r.RX_Weight_Male__c, IF(Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c, 100, 0), IF(AND(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c), 100, 0)
  )

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Score Between Goal?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Points_Based_on_Rank__c.field-meta.xml
<CustomField>
    <fullName>Points_Based_on_Rank__c</fullName>
    <label>Points Based on Rank</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Total_Workout_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Workout_Points__c</fullName>
    <inlineHelpText>Goal based points + Points based on Rank</inlineHelpText>
    <label>Total Workout Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Vault_Workout__c.field-meta.xml
<CustomField>
    <fullName>Vault_Workout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the Vault Workout</inlineHelpText>
    <label>Vault Workout</label>
    <referenceTo>Vault_Workout__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/Vault_Workout__c.object-meta.xml
<CustomObject>
    <label>Vault Workout</label>
    <nameField>
        <label>Vault Workouts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vault Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Is_Goal_Time__c.field-meta.xml
<CustomField>
    <fullName>Is_Goal_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Goal Time?</label>
    <type>Checkbox</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/classes/ScoreSubmissionTriggerHelper.cls
public without sharing class ScoreSubmissionTriggerHelper {
    public static void calculateRanking(List<Score_Submission__c> scoreList) {
        // get User info
        String usersName = UserInfo.getUserName();
        System.debug('Email address: ' + usersName);        
        
        List<Id> scoreListWorkoutIds = new List<Id>();
        Map<Id, Boolean> workoutIsGoalTimeMap = new Map<Id, Boolean>();
        for (Score_Submission__c s : scoreList) {
            scoreListWorkoutIds.add(s.Vault_Workout__c);
        }

        //! Doesn't handle BULK UPLOAD at this moment
        //? Pull all Workouts and put them in rank order
        String endQueryString; 
        if (scoreList[0].Is_Goal_Time__c) { 
            endQueryString = 'ASC'; //? Small to Larger if TIME (ASC)
        } else { 
            endQueryString = 'DESC'; //? Large to Smaller if NOT time (DESC)
        }

        String queryString = 'SELECT Calculated_Ranking_Points__c, Points_Based_on_Rank__c, Is_Goal_Time__c, Total_Workout_Points__c, Is_Score_Between_Goal__c FROM Score_Submission__c  WHERE Vault_Workout__r.Id In :scoreListWorkoutIds ORDER BY Calculated_Ranking_Points__c ';

        List<Score_Submission__c> existingScoresForWorkout = Database.query(queryString + endQueryString);

        Integer rankPoints = 100;
        Integer rankInterval = Integer.valueOf(System.Label.CompRankInterval);
        List<Score_Submission__c> updatedScores = new List<Score_Submission__c>(); 
        for (Score_Submission__c s : existingScoresForWorkout) {
            s.Points_Based_on_Rank__c = rankPoints;
            s.Total_Workout_Points__c = s.Is_Score_Between_Goal__c + s.Points_Based_on_Rank__c;
            updatedScores.add(s);
            rankPoints -= rankInterval;
        }
        System.debug('updatedScores' + updatedScores);
        for (Integer i=0; i < updatedScores.size(); i++) {
            if (i != 0) {
                if (updatedScores[i].Calculated_Ranking_Points__c == updatedScores[i-1].Calculated_Ranking_Points__c) {
                    updatedScores[i].Points_Based_on_Rank__c = updatedScores[i-1].Points_Based_on_Rank__c;
                    updatedScores[i].Total_Workout_Points__c = updatedScores[i].Is_Score_Between_Goal__c + updatedScores[i].Points_Based_on_Rank__c;
                }
            }
        }
		System.debug('updatedScores' + updatedScores);

        
        if (updatedScores.size() > 0) {
            update updatedScores;
        }
    }
}