SP_Vault_Comp/force-app/main/default/objects/Athlete__c/Athlete__c.object-meta.xml
<CustomObject>
    <label>Athlete</label>
    <nameField>
        <label>Athlete Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Athletes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Athlete__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>City, State</inlineHelpText>
    <label>Location</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Athlete__c/fields/Profile_Pic_URL__c.field-meta.xml
<CustomField>
    <fullName>Profile_Pic_URL__c</fullName>
    <label>Profile Pic URL</label>
    <type>Url</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Athlete__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <inlineHelpText>Sum of all Total Workout Points</inlineHelpText>
    <label>Total Points</label>
    <summarizedField>Score_Submission__c.Total_Workout_Points__c</summarizedField>
    <summaryForeignKey>Score_Submission__c.Athlete_Name__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/Score_Submission__c.object-meta.xml
<CustomObject>
    <label>Score Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Score Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Athlete_Name__c.field-meta.xml
<CustomField>
    <fullName>Athlete_Name__c</fullName>
    <inlineHelpText>Select the Athlete&apos;s Name</inlineHelpText>
    <label>Athlete&apos;s Name</label>
    <referenceTo>Athlete__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Score_1st__c.field-meta.xml
<CustomField>
    <fullName>Score_1st__c</fullName>
    <inlineHelpText>1st Value (Mins or Rounds)</inlineHelpText>
    <label>Score (1st)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Score_2nd__c.field-meta.xml
<CustomField>
    <fullName>Score_2nd__c</fullName>
    <inlineHelpText>2nd Value (Secs or Reps)</inlineHelpText>
    <label>Score (2nd)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Total_Workout_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Workout_Points__c</fullName>
    <inlineHelpText>Goal based points + Points based on Rank</inlineHelpText>
    <label>Total Workout Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Weight_Used__c.field-meta.xml
<CustomField>
    <fullName>Weight_Used__c</fullName>
    <inlineHelpText>Weight Used in Workout</inlineHelpText>
    <label>Weight Used</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Workout_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Workout_Order_Number__c</fullName>
    <formula>Vault_Workout__r.Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Workout Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/classes/AthleteLwcController.cls
public without sharing class AthleteLwcController {
    @AuraEnabled(cacheable=true)
    public static List<Athlete__c> getAllAthletes() {
        Id profileId = userinfo.getProfileId();
        String profileName = [Select Id,Name from Profile where Id=:profileId].Name;
        system.debug('ProfileName: '+profileName);

        List<Athlete__c> results = [
            SELECT Id, Name, Total_Points__c, Age__c, Location__c, Profile_Pic_URL__c 
            FROM Athlete__c 
            ORDER BY Total_Points__c DESC];

        System.debug(results);

        return results;
    }

    @AuraEnabled(cacheable=true)
    public static List<Athlete__c> getAllAthletesForOptions() {
        return [
            SELECT Id, Name, Profile_Pic_URL__c 
            FROM Athlete__c 
            ORDER BY Name ASC];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Score_Submission__c> getAllScoreSubmissions() {
        return [
            SELECT Id, Athlete_Name__c, Score_1st__c, Score_2nd__c, Weight_Used__c, Workout_Order_Number__c, Total_Workout_Points__c, CreatedDate
            FROM Score_Submission__c 
            ORDER BY Workout_Order_Number__c ASC];
    }
}