SP_Vault_Comp/force-app/main/default/objects/Athlete__c/Athlete__c.object-meta.xml
<CustomObject>
    <label>Athlete</label>
    <nameField>
        <label>Athlete Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Athletes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Athlete__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>City, State</inlineHelpText>
    <label>Location</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/Score_Submission__c.object-meta.xml
<CustomObject>
    <label>Score Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Score Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Athlete_Name__c.field-meta.xml
<CustomField>
    <fullName>Athlete_Name__c</fullName>
    <inlineHelpText>Select the Athlete&apos;s Name</inlineHelpText>
    <label>Athlete&apos;s Name</label>
    <referenceTo>Athlete__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Calculated_Points__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Points__c</fullName>
    <formula>Score_1st__c * Vault_Workout__r.Round_Value__c + Score_2nd__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Calculated_Ranking_Points__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Ranking_Points__c</fullName>
    <formula>IF( 
Vault_Workout__r.Is_Dumbbell__c , 
Calculated_Points__c + Calculated_Points__c * (0.01 * Weight_Used__c + 0.6), 
Calculated_Points__c + Calculated_Points__c * (0.005 * Weight_Used__c + 0.525)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Ranking Points</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Goal_High_Value__c.field-meta.xml
<CustomField>
    <fullName>Goal_High_Value__c</fullName>
    <formula>Vault_Workout__r.Goal_High_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Goal High Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Goal_Low_Value__c.field-meta.xml
<CustomField>
    <fullName>Goal_Low_Value__c</fullName>
    <formula>Vault_Workout__r.Goal_Low_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Goal Low Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Is_Goal_Time__c.field-meta.xml
<CustomField>
    <fullName>Is_Goal_Time__c</fullName>
    <formula>Vault_Workout__r.Is_Goal_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Goal Time?</label>
    <type>Checkbox</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Is_Score_Between_Goal__c.field-meta.xml
<CustomField>
    <fullName>Is_Score_Between_Goal__c</fullName>
    <formula>IF(Vault_Workout__r.Is_Goal_Time__c, 
  IF(Weight_Used__c &gt;= Vault_Workout__r.RX_Weight_Male__c, IF(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, 100, 0), IF(AND(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c), 100, 0)
  ), 

  IF(Weight_Used__c &gt;= Vault_Workout__r.RX_Weight_Male__c, IF(Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c, 100, 0), IF(AND(Calculated_Points__c &lt;= Vault_Workout__r.Goal_High_Value__c, Calculated_Points__c &gt;= Vault_Workout__r.Goal_Low_Value__c), 100, 0)
  )

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Score Between Goal?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Points_Based_on_Rank__c.field-meta.xml
<CustomField>
    <fullName>Points_Based_on_Rank__c</fullName>
    <label>Points Based on Rank</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Round_Value__c.field-meta.xml
<CustomField>
    <fullName>Round_Value__c</fullName>
    <formula>Vault_Workout__r.Round_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Round Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/RX_Weight_Male__c.field-meta.xml
<CustomField>
    <fullName>RX_Weight_Male__c</fullName>
    <formula>Vault_Workout__r.RX_Weight_Male__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RX Weight (Male)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Score_1st__c.field-meta.xml
<CustomField>
    <fullName>Score_1st__c</fullName>
    <inlineHelpText>1st Value (Mins or Rounds)</inlineHelpText>
    <label>Score (1st)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Score_2nd__c.field-meta.xml
<CustomField>
    <fullName>Score_2nd__c</fullName>
    <inlineHelpText>2nd Value (Secs or Reps)</inlineHelpText>
    <label>Score (2nd)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Total_Workout_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Workout_Points__c</fullName>
    <inlineHelpText>Goal based points + Points based on Rank</inlineHelpText>
    <label>Total Workout Points</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Vault_Workout__c.field-meta.xml
<CustomField>
    <fullName>Vault_Workout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the Vault Workout</inlineHelpText>
    <label>Vault Workout</label>
    <referenceTo>Vault_Workout__c</referenceTo>
    <relationshipLabel>Score Submissions</relationshipLabel>
    <relationshipName>Score_Submissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Score_Submission__c/fields/Weight_Used__c.field-meta.xml
<CustomField>
    <fullName>Weight_Used__c</fullName>
    <inlineHelpText>Weight Used in Workout</inlineHelpText>
    <label>Weight Used</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/Vault_Workout__c.object-meta.xml
<CustomObject>
    <label>Vault Workout</label>
    <nameField>
        <label>Vault Workouts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vault Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/First_Label__c.field-meta.xml
<CustomField>
    <fullName>First_Label__c</fullName>
    <defaultValue>&apos;Mins&apos;</defaultValue>
    <inlineHelpText>Label for the 1st Score Value</inlineHelpText>
    <label>First Label</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Goal_High_Value__c.field-meta.xml
<CustomField>
    <fullName>Goal_High_Value__c</fullName>
    <inlineHelpText>If it is Time based, the value will be in seconds, otherwise it will be in number of reps</inlineHelpText>
    <label>Goal High Value</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Goal_Low_Value__c.field-meta.xml
<CustomField>
    <fullName>Goal_Low_Value__c</fullName>
    <inlineHelpText>If it is Time based, the value will be in seconds, otherwise it will be in number of reps</inlineHelpText>
    <label>Goal Low Value</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Is_Dumbbell__c.field-meta.xml
<CustomField>
    <fullName>Is_Dumbbell__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Was the Workout designed primarily for Dumbbells?</inlineHelpText>
    <label>Is Dumbbell?</label>
    <type>Checkbox</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Is_Goal_Time__c.field-meta.xml
<CustomField>
    <fullName>Is_Goal_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Goal Time?</label>
    <type>Checkbox</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Round_Value__c.field-meta.xml
<CustomField>
    <fullName>Round_Value__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>If it is Time, Value will be 60 &quot;per round&quot; (Default = 1)</inlineHelpText>
    <label>Round Value</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/RX_Weight_Male__c.field-meta.xml
<CustomField>
    <fullName>RX_Weight_Male__c</fullName>
    <label>RX Weight (Male)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Second_Label__c.field-meta.xml
<CustomField>
    <fullName>Second_Label__c</fullName>
    <defaultValue>&apos;Secs&apos;</defaultValue>
    <inlineHelpText>Label for the 2nd Score Value</inlineHelpText>
    <label>Second Label</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/objects/Vault_Workout__c/fields/Workout_Date__c.field-meta.xml
<CustomField>
    <fullName>Workout_Date__c</fullName>
    <inlineHelpText>Monday of the Week the workout should be logged</inlineHelpText>
    <label>Workout Date</label>
    <type>Date</type>
</CustomField>

SP_Vault_Comp/force-app/main/default/classes/createScoreSubmissionTEST.cls
@isTest
private class createScoreSubmissionTEST {
    @isTest static void createScore_single() {
        //! Test data setup
        // Create a new Workout (Time Based)
        Vault_Workout__c workoutsToInsert = new Vault_Workout__c(
        	Name = 'Workout_Time',
        	Goal_Low_Value__c = 600, // 10 mins
	        Goal_High_Value__c = 900, // 15 mins
            Is_Dumbbell__c = TRUE,
            Is_Goal_Time__c = TRUE,
            Round_Value__c = 60,
            RX_Weight_Male__c = 40,
            First_Label__c = 'Mins',
            Second_Label__c = 'Secs',
            Order__c = 1,
            Workout_Date__c = System.today().addMonths(1)
        );
        insert workoutsToInsert;
        Vault_Workout__c workout = [SELECT Id, Name, Goal_Low_Value__c FROM Vault_Workout__c WHERE Name = 'Workout_Time' LIMIT 1];
        
        
        // Create Athletes
        Athlete__c athletesToInsert = new Athlete__c(
            Name = 'Test Testerson',
            Age__c = 35,
            Location__c = 'Dallas, TX'
        );
        insert athletesToInsert;
        Athlete__c athlete = [SELECT Id, Name, Age__c, Location__c FROM Athlete__c LIMIT 1];
        
        
        // Create a First Score Submissions for workout
        Score_Submission__c scoreSub = new Score_Submission__c(
            Athlete_Name__c = athlete.Id,
            Vault_Workout__c = workout.Id,
            Score_1st__c = 10,
            Score_2nd__c = 20,
            Weight_Used__c = 40
        );
        System.debug('TEST scoreSub: ' + scoreSub);
        // insert scoreSub;
        
        
        // Perform test
        Test.startTest();
        createScoreSubmission.createScore(scoreSub);
        Test.stopTest();


        // Validate Expected Results
        List<Score_Submission__c> subScores = [
            SELECT Id, Name, Athlete_Name__r.Name, Vault_Workout__r.Name, Score_1st__c, Score_2nd__c, Weight_Used__c, Calculated_Points__c, Calculated_Ranking_Points__c, Is_Score_Between_Goal__c, Points_Based_on_Rank__c, Total_Workout_Points__c
            FROM Score_Submission__c
            ORDER BY Name ASC];
        System.debug('subScores: ' + subScores);

        System.assertEquals(1, subScores.size());
        System.assertEquals(10, subScores[0].Score_1st__c);
        System.assertEquals(40, subScores[0].Weight_Used__c);
        System.assertEquals(100, subScores[0].Points_Based_on_Rank__c);
    }


    @isTest static void createScore_double_update() {
        //! Test data setup
        // Create a new Workout (Time Based)
        Vault_Workout__c workoutsToInsert = new Vault_Workout__c(
        	Name = 'Workout_Time',
        	Goal_Low_Value__c = 600, // 10 mins
	        Goal_High_Value__c = 900, // 15 mins
            Is_Dumbbell__c = TRUE,
            Is_Goal_Time__c = TRUE,
            Round_Value__c = 60,
            RX_Weight_Male__c = 40,
            First_Label__c = 'Mins',
            Second_Label__c = 'Secs',
            Order__c = 1,
            Workout_Date__c = System.today().addMonths(1)
        );
        insert workoutsToInsert;
        Vault_Workout__c workout = [SELECT Id, Name, Goal_Low_Value__c FROM Vault_Workout__c WHERE Name = 'Workout_Time' LIMIT 1];
        
        
        // Create Athletes
        Athlete__c athletesToInsert = new Athlete__c(
            Name = 'Test Testerson',
            Age__c = 35,
            Location__c = 'Dallas, TX'
        );
        insert athletesToInsert;
        Athlete__c athlete = [SELECT Id, Name, Age__c, Location__c FROM Athlete__c LIMIT 1];
        
        // Create a First Score Submissions for workout
        Score_Submission__c scoreSub1 = new Score_Submission__c(
            Athlete_Name__c = athlete.Id,
            Vault_Workout__c = workout.Id,
            Score_1st__c = 10,
            Score_2nd__c = 20,
            Weight_Used__c = 40
        );
        insert scoreSub1;
        
        // Create a Second Score Submissions for workout
        Score_Submission__c scoreSub2 = new Score_Submission__c(
            Athlete_Name__c = athlete.Id,
            Vault_Workout__c = workout.Id,
            Score_1st__c = 11,
            Score_2nd__c = 21,
            Weight_Used__c = 41
        );
        System.debug('TEST scoreSub2: ' + scoreSub2);
        // insert scoreSub;
        
        
        // Perform test
        Test.startTest();
        createScoreSubmission.createScore(scoreSub2);
        Test.stopTest();


        // Validate Expected Results
        List<Score_Submission__c> subScores = [
            SELECT Id, Name, Athlete_Name__r.Name, Vault_Workout__r.Name, Score_1st__c, Score_2nd__c, Weight_Used__c, Calculated_Points__c, Calculated_Ranking_Points__c, Is_Score_Between_Goal__c, Points_Based_on_Rank__c, Total_Workout_Points__c
            FROM Score_Submission__c
            ORDER BY Name ASC];
        System.debug('TEST subScores: ' + subScores);

        System.assertEquals(1, subScores.size());
        System.assertEquals(11, subScores[0].Score_1st__c);
        System.assertEquals(41, subScores[0].Weight_Used__c);
        System.assertEquals(100, subScores[0].Points_Based_on_Rank__c);
    }

    @isTest static void createScoreMany_getLastSubmitted() {
        //! Test data setup
        List<Integer> scores1 = new List<Integer>{10, 10, 11, 15, 16, 21};
        List<Integer> scores2 = new List<Integer>{15, 15, 30,  0, 45, 31};
        List<Integer> weights = new List<Integer>{30, 40, 40, 30, 40, 41};
        
        // Create a new Workout (Time Based)
        Vault_Workout__c workoutsToInsert = new Vault_Workout__c(
        	Name = 'Workout_Time',
        	Goal_Low_Value__c = 600, // 10 mins
	        Goal_High_Value__c = 900, // 15 mins
            Is_Dumbbell__c = TRUE,
            Is_Goal_Time__c = FALSE,
            Round_Value__c = 50,
            RX_Weight_Male__c = 40,
            First_Label__c = 'Rounds',
            Second_Label__c = 'Reps',
            Order__c = 1,
            Workout_Date__c = System.today().addMonths(1)
        );
        insert workoutsToInsert;
        
        Vault_Workout__c workout = [SELECT Id, Name, Goal_Low_Value__c FROM Vault_Workout__c WHERE Name = 'Workout_Time' LIMIT 1];
        System.debug('workout: ' + workout);
        
        
        // Create Athletes
        List<Athlete__c> athletesToInsert = new List<Athlete__c>();
        for (Integer i = 0; i < scores1.size(); i++) {
            Athlete__c ath = new Athlete__c(
                Name = 'Athlete_' + i+1,
                Age__c = 35 + i,
                Location__c = 'Dallas, TX'
            );
            athletesToInsert.add(ath);
        }
        insert athletesToInsert;
        List<Athlete__c> athletes = [SELECT Id, Name, Age__c, Location__c FROM Athlete__c];
        System.debug('athletes: ' + athletes);
        
        
        // Create new Score Submissions for workout
        List<Score_Submission__c> scoreSub = new List<Score_Submission__c>();
        Score_Submission__c lastScoreSub = new Score_Submission__c();
        for (Integer i = 0; i < scores1.size(); i++) {
            Score_Submission__c score = new Score_Submission__c(
                Athlete_Name__c = athletes[i].Id,
                Vault_Workout__c = workout.Id,
                Score_1st__c = scores1[i],
                Score_2nd__c = scores2[i],
                Weight_Used__c = weights[i]
            );
            scoreSub.add(score);
            if (i == scores1.size()-1) {
                lastScoreSub = score;
            }
        }
        insert scoreSub;
        
        System.debug('TEST lastScoreSub: ' + lastScoreSub);


        // Perform test
        Test.startTest();
        createScoreSubmission.getSubmittedScore(lastScoreSub);
        Test.stopTest();


        // Validate Expected Results
        List<Score_Submission__c> subScores = [
            SELECT Id, Name, Athlete_Name__r.Name, Vault_Workout__r.Name, Score_1st__c, Score_2nd__c, Weight_Used__c, Calculated_Points__c, Calculated_Ranking_Points__c, Is_Score_Between_Goal__c, Points_Based_on_Rank__c, Total_Workout_Points__c
            FROM Score_Submission__c
            ORDER BY Name DESC]; // to get the last one
        System.debug('TEST subScores: ' + subScores);

        System.assertEquals(6, subScores.size());
        System.assertEquals(21, subScores[0].Score_1st__c);
        System.assertEquals(41, subScores[0].Weight_Used__c);
        System.assertEquals(100, subScores[0].Points_Based_on_Rank__c);
    }
}